export default {
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",

  FETCH_MOVIES: "FETCH_MOVIES",
  ADD_MOVIE: "ADD_MOVIE",
  EDIT_MOVIE: "EDIT_MOVIE",
  DELETE_MOVIE: "DELETE_MOVIE",
  GET_MOVIE_BY_ID: "GET_MOVIE_BY_ID",
  FILTER_MOVIES: "FILTER_MOVIES",
  SORT_MOVIES: "SORT_MOVIES",
  SET_FILTER_GENRES: "SET_FILTER_GENRES",
  SET_SORT_BY: "SET_SORT_BY",
  SET_SEARCH_BY: "SET_SEARCH_BY",
}
